
library(CondIndTests)
library(ppcor)
library(dHSIC)
library(seqICP)
library(InvariantCausalPrediction)
library(MASS)
library(mgcv)
library(AER)
library(igraph)
library(hash)
show("You're all set!")

#install.packages("CondIndTests")
#install.packages("ppcor")
#install.packages("dHSIC")
#install.packages("seqICP")
#install.packages("InvariantCausalPrediction")
#install.packages("MASS")
#install.packages("mgcv")
#install.packages("AER")
#install.packages("igraph")
